apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
spec:
<<<<<<< HEAD
  params:
    - name: git-url
      type: string
    - name: image-url
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: kaniko
      taskRef:
        name: kaniko
      params:
        - name: git-url
          value: $(params.git-url)
        - name: image-url
          value: $(params.image-url)
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
=======
  tasks:
    - name: build-and-push
      taskRef:
        name: kaniko
>>>>>>> 6dc1e26133018ca07e10a72ecf62669e399c0cf3
