apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rails-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:SandeepRoshan/rails-k8s-argocd.git
    targetRevision: HEAD
    path: kubernetes_manifests/k8s_manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true